# -- Часть 1: O grand amor -- {-}


# Desafinado


<!-- João Gilberto (1985) | Люда Городничая (2001) -->
<!-- ----- | ------------- -->


João Gilberto (1985) 
<embed align="center" src="https://www.youtube.com/embed/n81JA6xSbcs" width="300"></embed>  

Люда Городничая (2001)
<embed align="center" src="https://www.youtube.com/embed/phoncqrWLv4" width="300"></embed>
</center> 

## Дисгармония {-}

<blockquote>
<cite>
(Музыка: А. Жобим, Слова: Д. Городничий )
</cite>
<pre>
Жизнь моя похожа на мелодию 
Любовь к тебе в ней создает гармонию 
Гармонию, где все звучит красиво и легко 
Но лишь одна в нём нота не попадает в аккорд 

Что то изменилось в отношении твоём 
Не горят теперь твои глаза когда поём 
Как будто ты нарочно изменила слова 
И теперь с тобой мы совпадаем едва ль 

  А ведь было время мы любили петь с тобой 
  И чтоб не пели, каждый знал прекрасно голос свой 
  Но вкусы резко изменись у тебя 
  А петь дуэтом не возможно не любя 

Вспомни же те чувства, 
чувства радостных тех дней 
Когда с тобой сидели, 
до рассвета песни пели. 
И может прислонишься ты опять ко мне 
И дисгармония изчезнит, 
Когда мы с тобою будем вместе. 
И мелодия сердец влюбленных 
зазвучит вновь в тишине. 

Да, мелодия опять найдется, 
Когда мы с тобою будем вместе. 
И с гармонией прекрасной песня 
зазвучит вновь в тишине. 

2012

F7M G7/5- 
Gm7 C9 Am7/5- D9- 
Gm7 A9- D7M9 D9- 
G7 G7 Gb7M Gb7/5-


F7M G7/5- Gm7 C9 Am7/5- D9- 
Gm7 A11/5+ Dm7(/4) E7 
A7M A11/5+ G13 Gb7


A7M Bb° Hm7 E6/9-
A7M Am9 Bm11(/5-) Bb7/5-
C7/5+ Db° Dm7 G13
Gm7 Ebm6 Gm7 C9- 

F7M G7/5- 
Gm7 C9 
Am7/5- D9- 
Bb7M Bbm6 Am7 Ab°
G7 Gb7/5+ 
Gb7/5+ 
G7 Gm7 C7 F C9- F6 F7M11+

</pre>
</blockquote>


# Corcovado 

<embed align="center" src="https://www.youtube.com/embed/ReE4jDvJVLw" width="300"></embed>  

<!-- 9srw5FRm5eA -->

<!-- _8xnQZ86fN4 -->


##  Тихим теплым вечером {-}

<blockquote>
<cite>
Музыка: А. Жобим. 
Слова: Д. Городничий
</cite> <pre>
Тихим теплым вечером
Лишь слышна гитара,
Играющая песню растованья

K небу звуки струн летят,
Превращаясь в нотный ряд,
В нотный ряд, где ноты звёзды
Светят нам в час этот поздний.


Как прекрасно всё вокруг:
Эти горы, этот звук.
А ведь ещё вчера так не казалось.

Вся жизнь моя казалась
Прожитой как попало,
Но вот сегодня встретил я тебя
И смыслом жизнь наполнилась моя.

2008

</pre>
</blockquote>


#  Samba de uno nota so 

<embed align="center" src="https://www.youtube.com/embed/naeq6fFmDpI?t=41s" width="300"></embed>  

##  Самба одной ноты {-}

<!-- Люди говорят так много слов -->
<!-- A за словами пустота,  -->
<!-- лишь пустота! -->
<!-- Вот и я пропел все ноты  -->
<!-- чтобы возвратиться вновь сюда,  -->
<!-- где нота та!  -->
<blockquote>
<cite>
Музыка: А. Жобим. 
Слова: Д. Городничий
</cite> 
<pre>
Это - самба одной ноты. 
Я тебе пою её.
Будут и другие ноты, 
Но лишь похожие на неё.

   Вот, пожалуйста, другая 
   нота, тоже лишь одна. 
   Только это не мешает 
   мне сказать как ты мне нужна!


Все кругом твердят мне что-то, 
Только за словами пустота, 
 лишь пустота!
Вот и я пропел все ноты 
чтобы возвратиться вновь сюда, 
 где нота та! 


Продолжaю петь я смело, 
Хоть одна лишь нота здесь. 
Ты поймешь не в нотах дело, 
А в тех чувствах, что у них есть. 

   Ты услышишь в них, я верю, 
   Глубину всех чувств моих 
   И откроешь сердца двери, 
   чтоб родился новый стих. 


Сколько слов и звуков бестолковых
Ото всюду слышим мы -
 С ума сойти! 
Может быть хоть эта босса-нова
Сможет этот шум пройти
 И тебя найти! 

...

Слышу комментарии я снова
Мол не много нот моих
 И слов моих.
Может быть хоть эта босса-нова
Объяснит, что лучше меньше их, 
 Но не пустых! 

2016

Dbm7 C7 
Bm11 Bb7/-5 
Dbm7 C7 
B7/4 Bb7/-5

Em7/9 A7/+5 
Dmaj7 Dm7 G7 
Dbm7 C7
Bm11 Bb7/-5 A6/9 

Dm7 G7
C7+ 

C7+ Cm7 
F7 Bbmaj7
B0 Bb7/-5 

Bb7/-5
||||||
|||||o
|o|o||
||||o|

Bm11 
|||||| 
|||||o 
||||||
|o|oo| 

</pre>
</blockquote>

# Insensatez 

<embed align="center" src="https://www.youtube.com/embed/PHIe9B5plDI" width="300"></embed>  

##  Безчувственный {-}


<blockquote>
<cite>
Музыка: А. Жобим. 
Слова: Д. Городничий
</cite> 
<pre>
как
я был жесток,
бездушен был
когда ты была со мною 

  ты 
  читала мне
  свои стихи
  и мы гуляли под луною 

пел
нам соловей
и не было
тебя нежней на всей планете

   но
   я не ценил
   и ты ушла
   и за это я в ответе 

как
теперь мне быть 
мне не забыть 
твои глаза твою улыбку 

   мир
   совсем другим 
   стал без тебя 
   и из-за моей ошибки 

ночь
теперь не та 
рассвет не тот 
В нем нет ни радости ни цвета 

   Как
   же мне вернуть 
   Тебя вернуть, 
   Как мне вернуть опять всё это?... 

                        2011
</pre>
</blockquote>


#  Dindi 

<embed align="center" src="https://www.youtube.com/embed/eEK6gyoR7LQ" width="300"></embed>  

##  динди {-}

<blockquote>
<cite>
Музыка: А. Жобим. 
Слова: Д. Городничий
</cite> 
<pre>
Небо, огромное небо
тучи летят в края, где я не был
Куда же летят они? -
Они летят к тебе.

Ветер свистит, напевает.
Как хорошо я его понимаю.
О ком он поёт? -
Поёт он о тебе.

О динди,
где найти мне такие слова
чтобы чувства свои передать.
Радость моя, ты моя Благодать.

Я так тебя люблю -
я тобою живу.
Ты - музыка моя
нежная, светлая.

Знаешь что, Динди,
Я лечу к тебе через мира
Словно птица на крыльях любви
Где б ни был ты
Мой любимый Динди...

2017
</pre>
</blockquote>

<!-- ### In English {} -->

<!-- <blockquote> -->
<!-- <cite> -->
<!-- Музыка: А. Жобим.  -->
<!-- Слова: Д. Городничий -->
<!-- </cite> <pre> -->

<!-- CM7 BbM7 -->
<!-- sky, so vast is the sky -->
<!-- CM7 BbM7 -->
<!-- where faraway clouds just wondering by -->
<!-- AM7 C#m7 -->
<!-- where do they go -->
<!-- F#m Bm7 -->
<!-- oh i don't know -->
<!-- E7 -->
<!-- don't know -->
<!-- CM7 BbM7 -->
<!-- wind that speaks to the leaves -->
<!-- CM7 BbM7 -->
<!-- telling stories that no one believes -->
<!-- AM7 C#m7 -->
<!-- stories of love -->
<!-- F#m Bm7 E7 -->
<!-- belong to you and me -->

<!-- [Chorus] -->
<!-- CM7 BbM7 -->
<!-- oh dindi -->
<!-- CM7 Gm7 -->
<!-- If I only had words I would say -->
<!-- F#m7 Fm7 Bb7 -->
<!-- All the beautiful things that I see -->
<!-- CM7 -->
<!-- When you're with me -->
<!-- BbM7 -->
<!-- Oh my dindi -->
<!-- CM7 BbM7 -->
<!-- Oh dindi -->
<!-- CM7 Am7 G#m7 Gm7 -->
<!-- Like the song of the wind in the trees -->
<!-- F#m7 Fm7 -->
<!-- That's how my heart is singing dindi -->
<!-- Bb7 -->
<!-- Happy dindi -->
<!-- CM7 Am7 F#m7 B7 -->
<!-- When you're with me -->

<!-- [Verse] -->
<!-- Em F#m7 -->
<!-- I love you more each day -->
<!-- B7 Em/G F#m7 B7 Em A7 -->
<!-- Yes I do, Yes I do -->
<!-- Dm7 A/G -->
<!-- I'd let you go away -->
<!-- Dm/F A/G Dm7 G7 -->
<!-- If you'd take me with you -->
<!-- CM7 BbM7 -->
<!-- Don't you know dindi -->
<!-- CM7 Gm7 -->
<!-- I'd be running and searching for you -->
<!-- F#m7 Fm7 -->
<!-- Like a river that can't find the sea -->
<!-- Bb7 CM7 -->
<!-- That would be me without you -->
<!-- BbM7 -->
<!-- My dindi -->

<!-- [Outro] -->
<!-- CM7 BbM7 -->
<!-- That would be me -->
<!-- CM7 -->
<!-- Without you my dindi -->

<!-- </pre> -->
<!-- </blockquote> -->




# Garota de Ipanema

<embed align="center" src="https://www.youtube.com/embed/91ofb4JEwQY" width="300"></embed>  


##  Garota de Ipanema  {-}

<blockquote>
<cite>
Музыка: А. Жобим. 
Слова: адаптировано от А. Иващенко 
</cite> 
<pre>
(Он: 
Вдоль по тропинке прибрежной 
над кручей отвесной 
Легка и прелестна, 
почти бестелесна, 
Походкой небесной проходит она.  

Столь грациозна, пленительна и несравненна, 
Что каждый готов угодить в этот плен,  
Но она неизменно проходит одна.  
 
  И словно громом на месте  
  Вновь поражён наповал я  
  Той красотой в каждом жесте, 
  Что в мечтах лишь своих рисовал я. 
  Ах, почему мы не вместе? 
 
Ах, зачем я несчастный не там, рядом с нею,  
Когда океанского солнца яснее 
над миром, как фея,  
Восходит она?  
Восходит она...  
)
 
(Она: 
Вдоль по тропинке над морем, и строен и гибок, 
Идёт он, танцуя, сквозь блики улыбок, 
Сквозь нежные вздохи прибрежных ундин. 
Двигаясь словно бы в ритме самбы, 
Я с ним прошлась по небесам бы, 
Но только он всегда уходит один. 
 
  Ах, как печально всё это! 
  Самый желанный на свете 
  Снова меня не заметит. 
  Снов и яви моей господин, 
  Опять он уходит один. 

По тропинке над морем, лёгкий как ветер, 
Уйдёт он опять, не заметив, не встретив 
Любви рассвет. Я смотрю ему вслед. 
Опять смотрю ему вслед... 
)
 
 
  И растворяясь в сиесте, 
  Вновь я любуюсь украдкой 
  Той красотой в каждом жесте, 
  Что терзает мой разум загадкой. 
  Ох, почему мы не вместе? 
 
О, почему, словно две 
нерифмованных строчки, 
Стремясь обойти запятые и точки, 
мы поодиночке 
По жизни идём? 
Идём и идём... 
</pre>
</blockquote>

# Só Danço Sambа

<embed align="center" src="https://www.youtube.com/embed/AVk-9LmaM8c" width="300"></embed>  


## Танцую самбу {-}

<blockquote>
<cite>
Музыка: А. Жобим. 
Слова: Д. Городничий (не окончена)
</cite> 
<pre>
Одну лишь самбу, 
и только самбу
Танцую я
одну лишь самбу, 
танцую самбу 
я.

   Это всё из-за тебя мой милый
   Не интересны больше мне 
   ни фокстрот, ни ча-ча-ча

Одну лишь самбу, 
и только самбу
Танцую я
одну лишь самбу, 
танцую самбу 
я.

   С тех пор как научил меня ты самбу
   Не интересны больше мне 
   ни фокстрот, ни ча-ча-ча


</pre>
</blockquote>

# Unfinished 

### Не уходи - Por causa de voce – Don't ever go away {-}


<cite>
Музыка: А. Жобим. 
Слова: Д. Городничий (не окончена)
</cite> 

### Я любил - Amor em paz – Once I loved {-}


<cite>
Музыка: А. Жобим. 
Слова: Д. Городничий (не окончена)
</cite> 

### о любовь - O grand amor
