---
title: "Troubleshooting: Printing UTF-8 (Russian) in R-marksdown, knitr"
author: "DG"
date: "January 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

<!-- # how to UTF-8 to 1251 in R -->
<!-- # https://tomizonor.wordpress.com/2013/04/17/file-utf8-windows/ -->
<!-- # https://www.smashingmagazine.com/2012/06/all-about-unicode-utf8-character-sets -->
<!-- # http://blog.rolffredheim.com/2013/01/r-and-foreign-characters.html -->



utf8 in yaml gives 'Reader error: invalid leading UTF-8 octet' on Windows

```{r}
library(knitr)
print(sessionInfo())
Sys.getlocale("LC_CTYPE") # "English_Canada.1252"
getOption("encoding"); #"native.enc"



#Sys.setlocale("LC_CTYPE", "russian") #"Russian_Russia.1251"
#options(encoding = 'UTF-8')

test2 = enc2utf8(c("привет","пока"))
write(test2, file="test2.txt")

dt <- data.frame(
  name=c("Борис Немцов","Martin Luter King"),
  year=c("2015","1968") 
)

dt$name; dt$name[1]
dt; kable(dt)
print(dt,encoding="windows-1251"); print(dt,encoding="UTF-8") #no effect

dt$name <- enc2utf8(dt$name )
dt; kable(dt)

```
